### ISSUE TITLE
`tags` / `stackTags` are `object`s, not `array`.

### ISSUE THREAD

**Issue by simonbuchan** [softprops/serverless-yml-schema#2]
The schema declares `tags` and `stackTags` with `"type": "array"`, but [the docs](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/) lists them as:

```yaml
provider:
  # ...
  stackTags: # Optional CF stack tags
    key: value
  # ...
  tags: # Optional service wide function tags
    foo: bar
    baz: qux
```
